### ISSUE TITLE
evince from terminal

### ISSUE THREAD

**Issue by szcf-weiya** [szcf-weiya/techNotes#32]
```bash
** (evince:24685): WARNING **: 22:56:29.944: AT-SPI: Could not obtain desktop path or name
```
the pdf file can be properly opened.

**Comment by szcf-weiya** [comment]
## strange icon on G40
![Screenshot from 2021-06-06 11-49-35](https://user-images.githubusercontent.com/13688320/120912055-a89ed700-c6be-11eb-8186-a31213343d7e.png)
install
```bash
sudo apt-get install gnome-tweak-tool
```
then run
```bash
gnome-tweaks
```
![Screenshot from 2021-06-06 12-00-30](https://user-images.githubusercontent.com/13688320/120912077-d552ee80-c6be-11eb-9f2d-682a24c1b6fe.png)
switch the theme from `HighContrast` to `Ubuntu-mono-light`.
now it becomes
![Screenshot from 2021-06-06 12-01-38](https://user-images.githubusercontent.com/13688320/120912098-fd425200-c6be-11eb-9751-1a1692935500.png)

**Comment by szcf-weiya** [comment]
## cannot open jupyter notebook on chpc
![image](https://user-images.githubusercontent.com/13688320/122636115-14029300-d11a-11eb-8e55-c1aa1af364eb.png)
since currently I cannot access the tmux session open on sandbox, I cannot get the detailed log info, so I try to open a new jupyter notebook, it throws that
```bash
$ jupyter notebook
...
[E 16:17:10.962 NotebookApp] Failed to write server-info to /storage01/users/s**********/.local/share/jupyter/runtime/nbserver-124579.json: [Errno 122] Disk quota exceeded: '/storage01/users/s**********/.local/share/jupyter/runtime/nbserver-124579.json'
Traceback (most recent call last):
  File "/users/s**********/miniconda3/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/users/s**********/miniconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/users/s**********/miniconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/users/s**********/miniconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1933, in start
    self.write_browser_open_file()
  File "/users/s**********/miniconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1842, in write_browser_open_file
    with open(self.browser_open_file, 'w', encoding='utf-8') as f:
OSError: [Errno 122] Disk quota exceeded: '/storage01/users/s**********/.local/share/jupyter/runtime/nbserver-124579-open.html'
```

**Comment by szcf-weiya** [comment]
## tips on iPad
when uploading photos to onedrive, select no more than 30 images, then the icon of onedrive would appear, otherwise, the icon won't show. Although it can be saved via `save to files` for more than 30 images, it will directly save the `.HEIC` format instead of `.jpg`.

**Comment by szcf-weiya** [comment]
## fail to download in chrome
failed on a HTTP website, 
try `wget` instead, but remember to use HTTP 
![image](https://user-images.githubusercontent.com/13688320/124924278-e11f3100-e02d-11eb-8f65-1b949c380f71.png)

**Comment by szcf-weiya** [comment]
## upgrade notes for fRLR

### upgrade document to `roxygen2`

```r
> devtools::document()
Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
Warning: The existing 'frlr1.Rd' file was not generated by roxygen2, and will not be overwritten.
Warning message:
roxygen2 requires Encoding: UTF-8 
```

and `UTF-8` to avoid the warning, https://stackoverflow.com/questions/51694929/warning-about-utf-8-with-roxygen2

### `not available for .Call() for package "fRLR"`

```bash
> frlr1(X, Y, COV)
Error in .Call("_fRLR_frlr1", PACKAGE = "fRLR", R_X, R_Y, R_COV) : 
  "_fRLR_frlr1" not available for .Call() for package "fRLR"
```

refer to https://stackoverflow.com/questions/58132832/error-function-is-not-available-for-call-for-package-x and  https://r-pkgs.org/src.html#cpp, and also need to update the NAMESPACE since by default it did not update after rebuilding,
```bash
> devtools::document()
Updating fRLR documentation
Loading fRLR
Writing NAMESPACE
Writing NAMESPACE
```

- load `fRLR.Rproj` in Rstudio, tried `Test Package`, but throws
```bash
Error: No testthat directories found in /media/weiya/PSSD/GitHub/fRLR
Execution halted

Exited with status 1.
```
following https://github.com/szcf-weiya/prin_curve/tree/master/tests, add such folder.

**Comment by szcf-weiya** [comment]
## upgrade memory
currently, it seems that there are two empty slots, but I remember that only two slots are available. 
```bash
$ sudo lshw -class memory 
[sudo] password for weiya: 
  *-cache:0                 
       description: L1 cache
       physical id: 2
       slot: L1 Cache
       size: 128KiB
       capacity: 128KiB
       capabilities: synchronous internal write-back data
       configuration: level=1
  *-cache:1
       description: L1 cache
       physical id: 3
       slot: L1 Cache
       size: 128KiB
       capacity: 128KiB
       capabilities: synchronous internal write-back instruction
       configuration: level=1
  *-cache:2
       description: L2 cache
       physical id: 4
       slot: L2 Cache
       size: 1MiB
       capacity: 1MiB
       capabilities: synchronous internal write-back unified
       configuration: level=2
  *-cache:3
       description: L3 cache
       physical id: 5
       slot: L3 Cache
       size: 6MiB
       capacity: 6MiB
       capabilities: synchronous internal write-back unified
       configuration: level=3
  *-memory
       description: System Memory
       physical id: 7
       slot: System board or motherboard
       size: 8GiB
     *-bank:0
          description: SODIMM DDR4 Synchronous 2133 MHz (0.5 ns)
          product: HMA451S6AFR8N-TF
          vendor: SK Hynix
          physical id: 0
          serial: 37182334
          slot: ChannelA-DIMM0
          size: 4GiB
          width: 64 bits
          clock: 2133MHz (0.5ns)
     *-bank:1
          description: [empty]
          physical id: 1
          slot: ChannelA-DIMM1
     *-bank:2
          description: SODIMM DDR4 Synchronous 2133 MHz (0.5 ns)
          product: M471A5143EB0-CPB
          vendor: Samsung
          physical id: 2
          serial: 23040000
          slot: ChannelB-DIMM0
          size: 4GiB
          width: 64 bits
          clock: 2133MHz (0.5ns)
     *-bank:3
          description: [empty]
          physical id: 3
          slot: ChannelB-DIMM1
  *-firmware
       description: BIOS
       vendor: LENOVO
       physical id: d
       version: R07ET62W (2.02 )
       date: 03/04/2016
       size: 128KiB
       capacity: 15MiB
       capabilities: pci pnp upgrade shadowing cdboot bootselect edd int13floppy720 int5printscreen int9keyboard int14serial int17printer int10video acpi usb biosbootspecification uefi
  *-memory UNCLAIMED
       description: Memory controller
       product: 100 Series/C230 Series Chipset Family Power Management Controller
       vendor: Intel Corporation
       physical id: 1f.2
       bus info: pci@0000:00:1f.2
       version: 31
       width: 32 bits
       clock: 33MHz (30.3ns)
       configuration: latency=0
       resources: memory:f2244000-f2247fff
```

other notes also mentioned that there is only two memory slots,
http://www.ibmbjb.com/thread-347311-1-1.html
![image](https://user-images.githubusercontent.com/13688320/128151734-91967c4b-ab4f-48d1-9c74-c9c4e735b297.png)
and https://gaopc.cn/6165.html
> 联想ThinkPad T460P在出厂的时候搭载了DDR4 2133MHZ 4GB内存，具有两个内存插槽，最大支持32GB内存扩展。

a candidate: https://www.amazon.com/Tech-PC4-17000-Notebook-Computer-AT16G1D4S2133ND8N12V/dp/B07KGLTT7V/

note that the maximum ram speed would depend on the CPU https://www.shareus.com/computer/how-to-check-maximum-ram-speed-supported-by-your-computer.html

and the supported RAM types of Intel® Core™ i5-6300HQ CPU is (refer to https://www.cpu-world.com/CPUs/Core_i5/Intel-Core%20i5-6300HQ%20Mobile%20processor.html)

> Supported memory: DDR3L-1600, LPDDR3-1866, DDR4-2133

**Comment by szcf-weiya** [comment]
![image](https://user-images.githubusercontent.com/13688320/128313509-9ae6ae36-1c6c-4aeb-b311-ae2be54e7d6b.png)

**Comment by szcf-weiya** [comment]
## 1m_ipv4_udp_receive_buffer_errors
![image](https://user-images.githubusercontent.com/13688320/129532171-f1c108dd-f4f8-44a8-a062-96e2ae8441a3.png)
currently
```bash
~$ sysctl net.core | grep mem
sysctl: permission denied on key 'net.core.bpf_jit_harden'
sysctl: permission denied on key 'net.core.bpf_jit_kallsyms'
sysctl: permission denied on key 'net.core.bpf_jit_limit'
net.core.optmem_max = 20480
net.core.rmem_default = 212992
net.core.rmem_max = 212992
net.core.wmem_default = 212992
net.core.wmem_max = 212992
```
then change it to (refer to https://cizixs.com/2018/01/13/linux-udp-packet-drop-debug/ and https://serverfault.com/questions/899364/netdata-ipv4-udp-errors
```bash
~$ sudo sysctl -w net.core.rmem_default=1048576
net.core.rmem_default = 1048576
~$ sudo sysctl -w net.core.rmem_max=2097152
net.core.rmem_max = 2097152
~$ sysctl net.core | grep mem
sysctl: permission denied on key 'net.core.bpf_jit_harden'
sysctl: permission denied on key 'net.core.bpf_jit_kallsyms'
sysctl: permission denied on key 'net.core.bpf_jit_limit'
net.core.optmem_max = 20480
net.core.rmem_default = 1048576
net.core.rmem_max = 2097152
net.core.wmem_default = 212992
net.core.wmem_max = 212992
```

**Comment by szcf-weiya** [comment]
different correspondent/receipt. The second one should be `z`, but it inherits the first one 

![Selection_2285](https://user-images.githubusercontent.com/13688320/132589964-13276bdd-5adf-4379-9504-e6b101d7d10d.png)

**Comment by szcf-weiya** [comment]
## history file left over from an older version of Julia
```julia
$ julia1.4.1 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.1 (2020-04-14)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

ERROR: Invalid history file (/users/s1155113972/.julia/logs/repl_history.jl) format:
If you have a history file left over from an older version of Julia,
try renaming or deleting it.
Invalid character: '\0' at line 9011
```

**Comment by szcf-weiya** [comment]
## deactivate email account
![image](https://user-images.githubusercontent.com/13688320/151953746-2250b616-a3b7-418b-bfbc-de535224d562.png)

**Comment by szcf-weiya** [comment]
## pipeline in convert?
how to avoid `tmp.png` in the following command.
```bash
convert fit-exp-1.png loss-exp-1.png +append tmp.png; eog tmp.png
```
